### PR TITLE
Update GmsCore to v0.2.21.212158

### PR DESCRIPTION
**Pull request by FintasticMan**
This pull request will update GmsCore to [v0.2.21.212158](https://github.com/microg/GmsCore/releases/tag/v0.2.21.212158).

### CODE REVIEW

**Comment by ungeskriptet** [comment]
I already made a pull request for 0.2.21.212158 and they still didn't merge it :(

**Comment by FintasticMan** [comment]
I just noticed that! Oh well, I guess it's not too bad, as you can just update via F-Droid once it's installed.

**Comment by DPTJKKVH** [comment]
Everyone says that but I never receive microG updates via F-Droid despite having the repo activated

**Comment by bananer** [comment]
> Everyone says that but I never receive microG updates via F-Droid despite having the repo activated

Sometimes this only works when I disable the other repos in F-Droid. Might be caused by a package with the same name ( https://f-droid.org/en/packages/com.google.android.gms/ ) in the official repo, but I never investigated further. Maybe someone would like to report this to F-Droid?

**Comment by bananer** [comment]
Closing this PR, see https://github.com/lineageos4microg/android_prebuilts_prebuiltapks/pull/54#issuecomment-895263811

**Comment by DPTJKKVH** [comment]
I will report it. Thanks for the info on why no updates are shown.

**Comment by bananer** [comment]
These seem to be relevant issues for F-Droid:

https://gitlab.com/fdroid/fdroidclient/-/issues/1904
https://gitlab.com/fdroid/fdroidclient/-/issues/2045

**Pull request closed without merging**
